files:
  include: "src/assets/styles/**/*.scss"
  ignore:
    - "src/assets/styles/base/*.scss"
syntax:
    include:
      - scss
      - sass
resolvers:
  indentation: 
    - 1
    - size: 2
  empty-line-between-blocks: 
    - 1
    - include: true
  property-sort-order:
    - 1
    - order: concentric
  attribute-quotes: 1
  border-zero: 1
  no-color-keywords: 1
  no-css-comments: 0
  no-important: 0
  no-trailing-zero: 1
  space-after-bang: 1
  space-before-bang: 1
  space-after-colon: 1
  space-before-colon: 1
  hex-length: 1
  url-quotes: 1
  zero-unit: 1
  hex-notation: 1
  final-newline: 1
options:
  optOut: false