files:
  include: "src/assets/styles/**/*.scss"
  ignore:
    - "src/assets/styles/base/*.scss"
rules:
  class-name-format:
    - 0
    - convention: hyphenatedlowercase
  leading-zero:
    - 0
  nesting-depth:
    - 0
    - max-depth: 3
  quotes:
    - 1
    - style: double
  indentation: 
    - 1
    - size: 2
  no-important: 
    - 0
  no-css-comments: 
    - 0
  no-value-vendor-prefix: 
    - 0