files:
  include: "src/assets/styles/components/_card.scss"
rules:
  class-name-format:
    - 2
    - convention: hyphenatedlowercase
  leading-zero:
    - 0
  nesting-depth:
    - 1
    - max-depth: 3
  quotes:
    - 1
    - style: double
