files:
  include: "src/assets/styles/*.scss"
  ignore:
    - "src/assets/styles/fonts.scss"
rules:
  class-name-format:
  - 2
  - convention: hyphenatedlowercase
  leading-zero:
  - 0
  nesting-depth:
    - 1
    -
      max-depth: 3
  quotes:
  - 1
  - style: double
